GET https://readinglist-portfolio.netlify.app HTTP/1.1
Content-Type: application/json

###

POST https://readinglist-portfolio.netlify.app HTTP/1.1
Content-Type: application/json

{
    "title": "Harry potter"
}

{
    "title": "Dark Tower"
}

###

PUT https://readinglist-portfolio.netlify.app HTTP/1.1
Content-Type: application/json

{
    "title": "Trader"
}

###

DELETE https://readinglist-portfolio.netlify.app HTTP/1.1
Content-Type: application/json